name: Deploy to AWS - DeleteProvider

on:
  push:
    branches:
      - test  # Se ejecutará solo cuando hagas push a la rama "test"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projectawsstore-deleteprovider:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/projectawsstore-deleteprovider:latest

      - name: Conectar a AWS EC2 y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DELETE }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Detener y eliminar el contenedor anterior si existe
            sudo docker stop delete-provider || true
            sudo docker rm delete-provider || true
            
            # Descargar la nueva versión desde Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/projectawsstore-deleteprovider:latest
            
            # Ejecutar el contenedor con el nombre correcto y los puertos adecuados
            sudo docker run -d -p 5001:5001 -p 4001:4001 --name delete-provider ${{ secrets.DOCKER_USERNAME }}/projectawsstore-deleteprovider:latest
